// Script assets have changed for v2.3.0 see
// https://help.yoyogames.com/hc/en-us/articles/360005277377 for more information

/// @description RENDERED STRANDS
function doMainStep() {
    
    // Ensure all required surfaces are initialized
    canvasCheck();

    // -------------------------------------------------------------------------
    // AUTOSAVE & LOADING LOGIC
    // -------------------------------------------------------------------------
    
    // The splash screen already asked. autoloading is only still 1 here if the
    // user pressed LOAD AUTOSAVE, so load straight away - no popup.
    if (autoloading == 1 && readyToCheckAutoloads == 1 && skipIntro == 0) {
        alFile = file_text_open_read("Autosave.txt");
        if (alFile != -1) {
            file_text_close(alFile);
            doAutoLoad();
        }
        autoloading = 0;
    }

    // Direct autoload if intro is skipped
    if (skipIntro == 1 && autoloading == 1) {
        alFile = file_text_open_read("Autosave.txt");
        if (alFile != -1) {
            doAutoLoad();
            autoloading = 0;
        }
        if (alFile != -1) file_text_close(alFile);
    }

    // Reset pointers for a fresh generation request
    if (pleaseGen == true) {
        updatePreRands(-1); // -1 targets all random values
        renderF = 0;        // Reset incremental set pointer
        renderH = 0;        // Reset per-set strand pointer
    }

    // Trigger an autosave on mouse release if system is ready
    if (mouse_check_button_released(mb_left) && demoMode == 0 && autosaving == 0 && readyToCheckAutoloads == 1) {
        autosaving = 1;
        doAutoSave();
        renderToSurf = 1; // Signal surface update
    }

    // -------------------------------------------------------------------------
    // INPUT HANDLING & LOGGING
    // -------------------------------------------------------------------------

    // Handle Generation trigger (G key or UI Button)
    if (keyboard_check_pressed(ord("G")) || (mouse_x > 1175 && mouse_x < 1375 && mouse_y > 67 && mouse_y < 97 && mouse_check_button_pressed(mb_left))) {
        doLogOnce = 9; // Internal state flag
        if (doLogOnce == 0) {
            logFile = file_text_open_append("LOG__" + string(current_time) + ".txt");
            file_text_write_string(logFile, "LogFile initiated");
            file_text_writeln(logFile);
            doLogOnce = 1;
        }
        if (doLogOnce == 1) {
            file_text_write_string(logFile, "Generated by G press");
            file_text_writeln(logFile);
        }
        if (doLogOnce == 1) {
            file_text_write_string(logFile, "QuickClear Surfaces");
            file_text_writeln(logFile);
        }
    }

    debugMsg = "Step Event";
    gpu_set_blendmode(bm_normal);
    
    // Clear wait objects if generation is cancelled or finished
    if (instance_exists(obj_wait)) {
        instance_destroy(obj_wait);
        generating = false;
        pleaseGen = false;
        renderF = 0;
        renderH = 0;
    }

    // UV Image Loader interaction
    if (point_in_rectangle(mouse_x, mouse_y, 985, 1029, 1017, 1059)) {
        smallTip = "UV image loader - Load in an image, preferrably square, to trace over";
        if (mouse_check_button_pressed(mb_left)) {
            // Re-instantiate the loader object
            if (instance_exists(obj_UV_Image_Loader)) instance_destroy(obj_UV_Image_Loader);
            instance_create_depth(0, 0, -100, obj_UV_Image_Loader);
        }
    }

    // Set GPU write enable to protect Alpha channel during draw
    gpu_set_colorwriteenable(true, true, true, false);

    // -------------------------------------------------------------------------
    // MAIN GENERATION LOOP
    // -------------------------------------------------------------------------

    if (doOnce) {
		
        if (maxScale < 1) maxScale = 1; // Scale safety fix

        // Check if any map needs regeneration (State 1)
        if (retrigger && !saving && (color_GenState == 1 or ao_GenState == 1 or mask_GenState == 1 or rgbMask_GenState == 1 or id_GenState == 1 or flow_GenState == 1 or norm_GenState == 1 or depth_GenState == 1 or frizz_GenState == 1)) {
            
			// Override img display during generation
				if      (doColor and color_GenState   == 1) img = 4;
				else if (doRGB   and rgbMask_GenState == 1) img = 0;
				else if (doDepth and depth_GenState   == 1) img = 3;
				else if (doMask and mask_GenState   == 1) img = 5;
				else if (doID and id_GenState   == 1) img = 2;
				else if (doFrizz and frizz_GenState   == 1) img = 8;
				else if (doAO and ao_GenState   == 1) img = 7;
				else if (doNorm and norm_GenState   == 1) img = 1;
				else if (doFlow and flow_GenState   == 1) img = 6;
				
				else img=9
				//doRGB=false//true
				/*
doNorm=false//true
doColor=false//true 4
doMask=false//true
doID=false//true
doDepth=false//true
doFlow=false //true 6
doAO=false  //7
doFrizz=false
generating=false//false
renderF=0 // incremental render - current set being rendered
*/



            // Validate all surfaces exist before plotting
            if (!surface_exists(canvas) or !surface_exists(mask_canvas) or !surface_exists(color_canvas) or !surface_exists(depth_canvas) or !surface_exists(flow_canvas) or !surface_exists(frizz_canvas) or !surface_exists(id_canvas) or !surface_exists(mask_canvas) or !surface_exists(nm_canvas)) {
                resetSurfaces();
            }


            // Initialization block for the first frame of a render
            if (renderF == 0) {
                curlRotator = 0;
                renderH = 0;
                idList = 0;   // V1.94 - was never reset, so ID map colours shifted run to run
                random_set_seed(seedVal);
                xx1 = 0; yy1 = 0; xx2 = 0; yy2 = 0;
                cache_strandPointer = 0;

                if (doLogOnce == 1) {
                    file_text_write_string(logFile, "Generating Triggered");
                    file_text_writeln(logFile);
                }

                canvasCheck();

                #region // MAP INITIALIZATION
                
                // Flow Map base color (Tangent Space Blue)
                if (dirBlue == 1 and dirHue == 0 and doFlow == 1 and flow_GenState != 2) {
                    gpu_set_blendmode(bm_add);
                    surface_set_target(flow_canvas);
                    var BlueCol = (make_color_rgb(128, 128, 255));
                    draw_set_color(BlueCol);
                    draw_rectangle(0, 0, 4095, 4095, 0);
                    surface_reset_target();
                    if (doLogOnce == 1) { file_text_write_string(logFile, "Flow Blue Overwash"); file_text_writeln(logFile); }
                    gpu_set_blendmode(bm_normal);
                }

                // RGB Mask Canvas setup
                if (rgbMask_GenState == 1) {
                    if (surface_exists(canvas)) {
                        surface_set_target(canvas);
                        draw_set_color(make_color_rgb(0, 0, 0));
                        draw_rectangle(0, 0, 4095, 4095, 0);
                        draw_set_color(c_white);
                        surface_reset_target();
                        if (doLogOnce == 1) { file_text_write_string(logFile, "RGB Mask Canvas fill"); file_text_writeln(logFile); }
                    } else {
                        resetSurfaces();
                        surface_set_target(canvas);
                        draw_set_color(make_color_rgb(0, 0, 0));
                        draw_rectangle(0, 0, 4095, 4095, 0);
                        draw_set_color(c_white);
                        surface_reset_target();
                    }
                }

                // Mask Canvas setup
                if (mask_GenState == 1) {
                    if (surface_exists(mask_canvas)) {
                        surface_set_target(mask_canvas);
                        draw_set_color(make_color_rgb(0, 0, 0));
                        draw_rectangle(0, 0, 4095, 4095, 0);
                        draw_set_color(c_white);
                        surface_reset_target();
                    } else {
                        resetSurfaces();
                        surface_set_target(mask_canvas);
                        draw_set_color(make_color_rgb(0, 0, 0));
                        draw_rectangle(0, 0, 4095, 4095, 0);
                        draw_set_color(c_white);
                        surface_reset_target();
                    }
                }

                // Color Canvas setup
                if (color_GenState == 1) {
                    if (surface_exists(color_canvas)) {
                        surface_set_target(color_canvas);
                        draw_set_color(colrBack);
                        draw_rectangle(0, 0, 4095, 4095, 0);
                        draw_set_color(c_white);
                        surface_reset_target();
                    } else {
                        resetSurfaces();
                        surface_set_target(color_canvas);
                        draw_set_color(make_color_rgb(0, 0, 0));
                        draw_rectangle(0, 0, 4095, 4095, 0);
                        draw_set_color(c_white);
                        surface_reset_target();
                    }
                }

                // Normal Map setup
                if (norm_GenState == 1) {
                    if (surface_exists(nm_canvas)) {
                        surface_set_target(nm_canvas);
                        if (moreHairs == 1) draw_set_color(make_color_rgb(0, 0, 0));
                        if (moreHairs == 0) draw_set_color(make_color_rgb(128, 128, 255));
                        draw_rectangle(0, 0, 4095, 4095, 0);
                        draw_set_color(c_white);
                        surface_reset_target();
                    } else {
                        resetSurfaces();
                        surface_set_target(nm_canvas);
                        if (oldNormDraw == 0) draw_set_color(make_color_rgb(0, 0, 0));
                        if (oldNormDraw == 1) draw_set_color(make_color_rgb(128, 128, 255));
                        draw_rectangle(0, 0, 4095, 4095, 0);
                        draw_set_color(c_white);
                        surface_reset_target();
                    }
                }

                // ID Map setup
                if (id_GenState == 1) {
                    if (surface_exists(id_canvas)) {
                        surface_set_target(id_canvas);
                        draw_set_color(make_color_rgb(0, 0, 0));
                        draw_rectangle(0, 0, 4095, 4095, 0);
                        draw_set_color(c_white);
                        surface_reset_target();
                    } else {
                        resetSurfaces();
                        surface_set_target(id_canvas);
                        draw_set_color(make_color_rgb(0, 0, 0));
                        draw_rectangle(0, 0, 4095, 4095, 0);
                        draw_set_color(c_white);
                        surface_reset_target();
                    }
                }

                // Depth Map setup
                if (depth_GenState == 1) {
                    if (surface_exists(depth_canvas)) {
                        surface_set_target(depth_canvas);
                        draw_set_color(make_color_rgb(0, 0, 0));
                        draw_rectangle(0, 0, 4095, 4095, 0);
                        draw_set_color(c_white);
                        surface_reset_target();
                    } else {
                        resetSurfaces();
                        surface_set_target(depth_canvas);
                        draw_set_color(make_color_rgb(0, 0, 0));
                        draw_rectangle(0, 0, 4095, 4095, 0);
                        draw_set_color(c_white);
                        surface_reset_target();
                    }
                }

                // Frizz Map setup
                if (frizz_GenState == 1) {
                    if (surface_exists(frizz_canvas)) {
                        surface_set_target(frizz_canvas);
                        draw_set_color(make_color_rgb(128, 128, 128));
                        draw_rectangle(0, 0, 4095, 4095, 0);
                        draw_set_color(c_white);
                        surface_reset_target();
                    } else {
                        resetSurfaces();
                        surface_set_target(frizz_canvas);
                        draw_set_color(make_color_rgb(128, 128, 128));
                        draw_rectangle(0, 0, 4095, 4095, 0);
                        draw_set_color(c_white);
                        surface_reset_target();
                    }
                }

                // Flow Map setup
                if (flow_GenState == 1) {
                    if (surface_exists(flow_canvas)) {
                        surface_set_target(flow_canvas);
                        draw_set_color(make_color_rgb(0, 0, 0));
                        draw_rectangle(0, 0, 4095, 4095, 0);
                        draw_set_color(c_white);
                        surface_reset_target();
                    } else {
                        resetSurfaces();
                        surface_set_target(flow_canvas);
                        draw_set_color(make_color_rgb(0, 0, 0));
                        draw_rectangle(0, 0, 4095, 4095, 0);
                        draw_set_color(c_white);
                        surface_reset_target();
                    }
                }

                // AO Map setup
                if (ao_GenState == 1) {
                    if (surface_exists(ao_canvas)) {
                        surface_set_target(ao_canvas);
                        draw_set_color(make_color_rgb(200, 200, 200));
                        draw_rectangle(0, 0, 4095, 4095, 0);
                        draw_set_color(c_white);
                        surface_reset_target();
                    } else {
                        resetSurfaces();
                        surface_set_target(ao_canvas);
                        draw_set_color(make_color_rgb(200, 200, 200));
                        draw_rectangle(0, 0, 4095, 4095, 0);
                        draw_set_color(c_white);
                        surface_reset_target();
                    }
                }

                #endregion
            }

            strandCount = 0;
            {
                maxStrands = 2200;
                rootRange = random((life / (rootPosition * 50))) / 3;

                #region // MAIN CALCULATION - REFACTORED v2.0

                var thicknessBase = 1.0;
                curlRotator = 0;

                // Point cache arrays - Pre-allocated for high-speed calculation
                var pt_finalX = array_create(4000, 0);
                var pt_yy = array_create(4000, 0);
                var pt_scA = array_create(4000, 0);
                var pt_a = array_create(4000, 1);
                var pt_colr = array_create(4000, c_white);
                var pt_colrCustom = array_create(4000, c_white);
                var pt_depthTone = array_create(4000, c_white);
                var pt_ang = array_create(4000, 0);
                var pt_curl = array_create(4000, 0);
                var pt_sub = array_create(4000, 0);
                var pt_prevX = array_create(4000, 0);
                var pt_count = 0;

                // Current batch index
                var f = renderF;

                // -------------------------------------------------------------
                // V1.94 PER-SET SEED
                // The preview (mainCalc) and the pre-random tables (updatePreRands)
                // both seed from randomSeedVal[set] at the start of every set. The
                // renderer used to seed ONCE, from seedVal, at renderF==0 - and it
                // renders one set per frame, so by the time set 1 began the stream
                // had been moved on by set 0's draws AND by whatever mainCalc did in
                // the Draw event in between. That made the render disagree with the
                // preview and, worse, not reproduce itself. Seeding here puts every
                // set on its own seed, frame boundaries and preview activity be
                // damned, and matches where the cached strand tables came from.
                // -------------------------------------------------------------
                // The +f*7919 keeps each set on its own stream. randomSeedVal
                // defaults to 1 for every set, so seeding with it alone would make
                // every set an exact clone beyond the cached strands.
                random_set_seed(randomSeedVal[f] + (f * 7919));
                if (doLogOnce == 1) { file_text_write_string(logFile, "SET ID:" + string(f)); file_text_writeln(logFile); }
                
                setID = f;
                sx = xx;
                if (idMode == 1) idChoice = colorIDarray[f];
                sc = 1;
                a = 1;

                // Calculate Strand Set properties
                // V1.94 - was random(lifeVariant*2), re-rolled here. Two problems:
                // it disagreed with the preview (which uses preRandLifeVariant), and
                // lifeVariant is not assigned until inside the strand loop below, so
                // this was rolling against the PREVIOUS set's variance.
                // Guarded like mainCalc: an override of 0 must not collapse the set.
                if (strandLengthOverride[f] > 0) hairLength = strandLengthOverride[f] + preRandLifeVariant[f];
                if (setCountOverrode[f] == 1) strandSet = strandCountOverride[f]; else strandSet = strands;

                // -------------------------------------------------------------
                // PER-STRAND GENERATION LOOP
                // -------------------------------------------------------------
                for (h = 0; h < strandSet; h++) {
                    checkSum++;
                    var d = clamp(floor((255 / strandSet) * h), 20, 255);
                    depthTone = make_color_rgb(d, d, d);
                    dpth = random(100) / 100;
                    // V1.94 - every other per-strand value below reuses the preview's
                    // cached value for the first maxPreviewStrandsPerSet strands; dpth
                    // was the one that did not, so the render's depth/tone blend never
                    // matched what the preview showed.
                    if (h < maxPreviewStrandsPerSet) dpth = strandDepth[f, h];
					xxx = (1024 / 11) * h
					yyy = 400
                    subSpriteChoice = preRandSubSprite[f, h];
                    angChoice = preRandAngChoice[f, h];
                    // V1.92 - identical rule to doCalc. The old code re-rolled
                    // random_range once per active override AFTER taking the cached
                    // preview value, which both discarded that value and pulled extra
                    // numbers out of the random stream - so an overridden set drifted
                    // away from its own preview. One draw, clamps chosen up front.
                    var _thickVaryS = setThickVaryAdj[f];   // per-set variance
                    var _tbLo = 0.8;
                    var _tbHi = maxScale;
                    if (setThickMinOverrode[f] == 1) _tbLo = setThickMinAdj[f];
                    if (setThickMaxOverrode[f] == 1) _tbHi = setThickMaxAdj[f];
                    thicknessBase = clamp(random_range(_thickVaryS / 100, _thickVaryS / 20), _tbLo, _tbHi);

                    // The first maxPreviewStrandsPerSet strands reuse exactly what the
                    // preview drew, so preview and final are the same strands.
                    if (h < maxPreviewStrandsPerSet) thicknessBase = strandThickBase[f, h];

                    if (idMode == 0) {
                        idChoice = colorIDarray[idList];
                        idList++;
                        if (idList > strandIDsize) idList = 0;
                    }

                    lifeVariant = strandSetVariAdj[f];
                    
                    // Spacing and initial X position logic
                    xx = (320 - (strandSetSpaceAdj[f] * 10)) + ((strandSetSpaceAdj[f] * 10) / 2) + ((random_range(0, strandSetSpaceAdj[f] * 10) + (f * ((setDistance * 2) * 5))));
                    if (h < maxPreviewStrandsPerSet) xx = strandXX[f, h];
                    setXpos = (320 - (strandSetSpaceAdj[f] * 10)) + (strandSetSpaceAdj[f] * 10) + (f * ((setDistance * 2) * 5));
                    sx = xx;

                    life = random_range(
                        clamp(hairLength * (1 - (lifeVariant / 100)), 10, 3900),
                        clamp(hairLength * (1 + (lifeVariant / 100)), 10, 3900)
                    );
                    if (h < maxPreviewStrandsPerSet) life = strandLife[f, h];

                    scaleIn = life * 0.75;
                    scaleOut = life * 0.12;
                    avgLife = median(life, avgLife);

                    freq = random_range(strandSetWaveFreqMinAdj[f], strandSetWaveFreqMaxAdj[f]);
                    if (h < maxPreviewStrandsPerSet) freq = strandFrq[f, h];

                    amp = random(1000) / 10000;
                    if (h < maxPreviewStrandsPerSet) amp = strandAmp[f, h];

                    yp = 0;
                    // V1.94 - was random(yjit)+120, i.e. [120,320). preRandYY (which the
                    // cached strands below 100 come from) is [-yRan, yRan*3)+120, so the
                    // uncached strands used to sit in a different, wider band - a visible
                    // seam in the root line at strand 100.
                    yy = (random_range(-strandYRanRange[f], strandYRanRange[f] * 3) + 120) + yOffset[f];
                    if (h < maxPreviewStrandsPerSet) yy = strandYY[f, h] + yOffset[f];

                    nx = 0;
                    rootRange = random((rootPosition * 50)) / 3;
                    if (h < maxPreviewStrandsPerSet) rootRange = strandRootRange[f, h];

                    root = (random_range(round(random_range(0, (rootPosition * 50))), (rootPosition * 50) + rootRange));
                    if (h < maxPreviewStrandsPerSet) root = strandRoot[f, h];

                    tip = ((tipPosition * 10));

                    if (pleaseGen == true) {
                        strandDecision = random(100) / 100;
                        if (h < maxPreviewStrandsPerSet) strandDecision = strandDecide[f, h];
                    }

                    if (pleaseGen == true) {
                        straggleChoice = choose(editingPath[0], editingPath[1], editingPath[2]);
                        if (h < maxPreviewStrandsPerSet) straggleChoice = strandStraggleChoice[f, h];
                    }

                    cache_strandPointer = 0;
                    if (doLogOnce == 1) { file_text_write_string(logFile, "Strand ID: " + string(h) + " Life:" + string(life)); file_text_writeln(logFile); }

                    // Setup thickness and color parameters for the point-loop
                    var t_minScale = setThickMinAdj[f];
                    var t_maxScale = setThickMaxAdj[f];
                    var cmx = setRootThickAdj[f] / 30;              // V1.91 per-set
                    var cmy = setTipThickAdj[f] / 30;               // V1.91 per-set
                    // V1.94 - dpthAdd was re-rolled inside the point loop; the preview
                    // uses one value per strand from preRandDepthAdd. Same table now, so
                    // the depth/colour blend agrees. (Reinstating the per-point speckle
                    // means moving this line back into the loop as random_range.)
                    dpthAdd = preRandDepthAdd[f, min(h, 99)];
                    var _fadeInS  = clamp(setFadeInAdj[f],  1, 40); // V1.91 per-set
                    var _fadeOutS = clamp(setFadeOutAdj[f], 1, 40); // V1.91 per-set
                    var padFactor = 0.05 + (padding / 1000);
                    var tMin = t_minScale * padFactor;
                    var tMax = t_maxScale * padFactor;
                    var tMax2 = tMax * 2;

                    // ---------------------------------------------------------
                    // V1.90 NOISE - per-strand setup. Phases are hashed from the
                    // set seed + set/strand index so the deviation is seed-driven
                    // and repeatable WITHOUT drawing from the random stream.
                    // noiseAmt = 0 skips all of this and the loop cost with it.
                    // ---------------------------------------------------------
                    noiseOn = 0;
                    noiseP1 = 0; noiseP2 = 0; noiseP3 = 0;
                    noiseS1 = 0; noiseS2 = 0; noiseS3 = 0;
                    noiseAmpS = 0;

                    var _noiseAmtS  = setNoiseAmtAdj[f];    // V1.91 per-set
                    var _noiseFreqS = setNoiseFreqAdj[f];   // V1.91 per-set

                    if (_noiseAmtS > 0) {
                        noiseOn = 1;
                        var _nA = (h * 12.9898) + (f * 78.233) + (randomSeedVal[f] * 37.719);
                        noiseP1 = frac(abs(sin(_nA)         * 43758.5453)) * 1440;
                        noiseP2 = frac(abs(sin(_nA + 17.31) * 43758.5453)) * 1440;
                        noiseP3 = frac(abs(sin(_nA + 53.77) * 43758.5453)) * 1440;
                        // Frequency slider scales all three octaves together.
                        // noiseFreq 10 = neutral (1.0), 0 = 0.2, 40 = 3.4.
                        var _nFMul = 0.2 + (_noiseFreqS * 0.08);
                        var _nCyc = 1440 / max(life, 1);
                        noiseS1 = _nCyc * 1.0 * _nFMul;   // slow sweep down the fibre
                        noiseS2 = _nCyc * 2.7 * _nFMul;
                        noiseS3 = _nCyc * 6.3 * _nFMul;
                        noiseAmpS = (_noiseAmtS * 0.025) * (life * noiseScale);
                    }

                    // Color channel extraction for optimized blending
                    var cRvA = color_get_red(customColVarA); var cGvA = color_get_green(customColVarA); var cBvA = color_get_blue(customColVarA);
                    var cRvB = color_get_red(customColVarB); var cGvB = color_get_green(customColVarB); var cBvB = color_get_blue(customColVarB);
                    var cRroot = color_get_red(customRootCol); var cGroot = color_get_green(customRootCol); var cBroot = color_get_blue(customRootCol);
                    var cRtip = color_get_red(customTipCol); var cGtip = color_get_green(customTipCol); var cBtip = color_get_blue(customTipCol);

                   // ---------------------------------------------------------
                    // PASS 1: POINT CALCULATION — LUT version
                    // ---------------------------------------------------------
                    pt_count = 0;
                    var prevX_cache = xOffset[f] + xx;   // V1.94 - finalX includes xOffset
                    a = 1;
                    var _lifeRcp = 1 / life; // avoid repeated division

                    for (n = 0; n < life; n++) {
                        // Root and tip gradients
                        // V1.94 - the preview has these else branches; without them the
                        // render latched the last computed rt/tp and smeared root colour
                        // down the strand.
                        if (root > n) { rt = 1 - (clamp((n * (3800 / life)) / root, 0, 1)); } else { rt = 0.01; }
                        if (life - tip > n) { tp = 1 - (clamp(abs((life - tip - n)) / (tip * (life / 3800)), 0, 1)); } else { tp = 1; }

                        // Thickness — LUT (dsin/dcos degree-based, exact match)
                        var _li90  = round(n * _lifeRcp * 360) mod 1440;
                        var _li180 = round(n * _lifeRcp * 720) mod 1440;
                        var scx = lerp(tMin, tMax2, lut_sin[_li90]);
                        var scy = lerp(tMin, tMax2, lut_cos[_li90]);
                        var scz = lerp(tMin, tMax,  lut_sin[_li180]);
                        var tA = lerp(scx, scz, cmx);
                        var tB = lerp(scy, scz, cmy);
                        var scA = (clamp((tA + tB) * thicknessBase, 0.15, 100) / 2);

                        colr = make_color_rgb(clamp(255 * (dpth + dpthAdd), 0, 255), 255 * rt, 255 * tp);

                        // Custom colour — pre-extracted channels
                        var blend = clamp(dpth + dpthAdd, 0, 1);
                        var cv_r = lerp(cRvA, cRvB, blend); var cv_g = lerp(cGvA, cGvB, blend); var cv_b = lerp(cBvA, cBvB, blend);
                        cv_r = lerp(cv_r, cRroot, rt); cv_g = lerp(cv_g, cGroot, rt); cv_b = lerp(cv_b, cBroot, rt);
                        cv_r = lerp(cv_r, cRtip,  tp); cv_g = lerp(cv_g, cGtip,  tp); cv_b = lerp(cv_b, cBtip,  tp);
                        colrCustom = make_color_rgb(cv_r, cv_g, cv_b);

                        // Alpha fade
                        a = 1;
                        // V1.91 per-set. The old code clamped the GLOBAL fadeIn /
                        // fadeOut from inside the point loop; the per-set values are
                        // clamped once, above, instead.
                        if (n > life - ((_fadeOutS / 40) * (life / 2))) { a = clamp((life - n) / ((_fadeOutS / 40) * (life / 2)), 0, 1); }
                        if (n < ((_fadeInS / 40) * (life / 2)) + 1)     { a = clamp(n / ((_fadeInS / 40) * (life / 2)), 0, 1); }

                        // Wave — LUT with amp inside angle (matches original sin(degtorad(n*freq)*amp))
                        var _liDev  = round(n * freq * 4)       mod 1440; // sin(degtorad(n*freq))
                        var _liWave = round(n * freq * amp * 4) mod 1440; // sin(degtorad(n*freq)*amp)
                        deviationFromX = lut_sin[_liDev];
                        curlRotator += preRandCurling[f, h];
                        nx = xx + (lut_sin[_liWave] * ((yy - yOffset[f]) / 100));

                        var xA = lerp(0, path_get_x(editingPath[0], (n - lifeVariant) / (4096 + (strandSetMixerOffsetAdj1[f] * 100))), strandSetMixerAdj1[f]);
                        var xB = lerp(0, path_get_x(editingPath[1], (n - lifeVariant) / (4096 + (strandSetMixerOffsetAdj2[f] * 100))), strandSetMixerAdj2[f]);
                        var xC = lerp(0, path_get_x(editingPath[2], (n - lifeVariant) / (4096 + (strandSetMixerOffsetAdj3[f] * 100))), strandSetMixerAdj3[f]);
                        var tempX = (lerp(lerp(xA, xB, 0.5), xC, 0.5) / lifeVariant) * 8;

                        straggleXX = lerp(xx + tempX, setXpos, (n / 3000) * (strandSetTaperAdj[f] * 0.01));
                        var algFinalX = lerp((lerp(xx, nx, (strandSetWavynessAdj[f] * 0.01) * ampFactor)), straggleXX, 0.5 + ((lifeVariant - 50) / 100));
                        var algTaper  = lerp(algFinalX, setXpos, (n / life) * (clamp(strandSetTaperAdj[f], 1, strandSetTaperAdj[f]) * 0.01));

                        // V1.90 NOISE - gradual left/right deviation, root anchored
                        // so the fibre stays continuous and connected at the root.
                        var _nzOfs = 0;
                        if (noiseOn == 1) {
                            var _n1 = lut_sin[round(noiseP1 + (n * noiseS1)) mod 1440];
                            var _n2 = lut_sin[round(noiseP2 + (n * noiseS2)) mod 1440];
                            var _n3 = lut_sin[round(noiseP3 + (n * noiseS3)) mod 1440];
                            _nzOfs = ((_n1 * 0.62) + (_n2 * 0.28) + (_n3 * 0.10)) * noiseAmpS * (n * _lifeRcp);
                        }

                        finalX = xOffset[f] + algTaper + _nzOfs;

                        pt_finalX[pt_count] = finalX; pt_yy[pt_count] = yy; pt_scA[pt_count] = scA; pt_a[pt_count] = a;
                        pt_colr[pt_count] = colr; pt_colrCustom[pt_count] = colrCustom; pt_depthTone[pt_count] = depthTone;
                        pt_ang[pt_count] = angChoice; pt_curl[pt_count] = curlRotator; pt_sub[pt_count] = subSpriteChoice;
                        pt_prevX[pt_count] = prevX_cache;

                        prevX_cache = finalX;
                        pt_count++;
                        yy++;
                        yp++;
                    }

                    // ---------------------------------------------------------
                    // PASS 2: BATCHED RENDERING TO SURFACES
                    // ---------------------------------------------------------

                    // RGB Mask Draw
                    if (doRGB and rgbMask_GenState == 1) {
                        surface_set_target(canvas);
                        for (_pi = 0; _pi < pt_count; _pi++) {
                            if (moreHairs == 0) draw_sprite_ext(spr_strander, pt_sub[_pi], pt_finalX[_pi], pt_yy[_pi], pt_scA[_pi], pt_scA[_pi], 0, pt_colr[_pi], pt_a[_pi]);
                            if (moreHairs == 1) draw_sprite_ext(spr_strander, pt_sub[_pi], pt_finalX[_pi], pt_yy[_pi], pt_scA[_pi], pt_scA[_pi], pt_ang[_pi] + pt_curl[_pi], pt_colr[_pi], pt_a[_pi]);
                        }
                        surface_reset_target();
                        rgbMask_GenState = 1;
                        if (doLogOnce == 1) { file_text_write_string(logFile, "PLOT RGB canvas (batched)"); file_text_writeln(logFile); }
                    }

                    // Color Pass Draw
                    if (doColor and color_GenState == 1) {
                        surface_set_target(color_canvas);
                        for (_pi = 0; _pi < pt_count; _pi++) {
                            if (moreHairs == 0) draw_sprite_ext(spr_strander, pt_sub[_pi], pt_finalX[_pi], pt_yy[_pi], pt_scA[_pi], pt_scA[_pi], 0, pt_colrCustom[_pi], pt_a[_pi]);
                            if (moreHairs == 1) draw_sprite_ext(spr_strander, pt_sub[_pi], pt_finalX[_pi], pt_yy[_pi], pt_scA[_pi], pt_scA[_pi], pt_ang[_pi] + pt_curl[_pi], pt_colrCustom[_pi], pt_a[_pi]);
                        }
                        surface_reset_target();
                        if (doLogOnce == 1) { file_text_write_string(logFile, "PLOT COLOR canvas (batched)"); file_text_writeln(logFile); }
                    }

                    // Normal Map Draw
                    if (doNorm and norm_GenState == 1) {
                        surface_set_target(nm_canvas);
                        for (_pi = 0; _pi < pt_count; _pi++) {
                            if (moreHairs == 1) {
                                gpu_set_blendmode(bm_normal);
                                draw_sprite_ext(spr_stranderBUMP, pt_sub[_pi], pt_finalX[_pi], pt_yy[_pi], pt_scA[_pi], pt_scA[_pi], pt_ang[_pi] + pt_curl[_pi], c_white, pt_a[_pi] * 0.51);
                            }
                            if (moreHairs == 0) {
                                draw_sprite_ext(spr_nm, 0, pt_finalX[_pi], pt_yy[_pi], pt_scA[_pi] * 1.3, pt_scA[_pi] * 1.3, 0, c_white, pt_a[_pi] * 0.25);
                                draw_sprite_ext(spr_nm, 0, pt_finalX[_pi], pt_yy[_pi], pt_scA[_pi] * 1.2, pt_scA[_pi] * 1.2, 0, c_white, pt_a[_pi] * 0.50);
                                draw_sprite_ext(spr_nm, 0, pt_finalX[_pi], pt_yy[_pi], pt_scA[_pi] * 1.1, pt_scA[_pi] * 1.1, 0, c_white, pt_a[_pi] * 0.75);
                                draw_sprite_ext(spr_nm, 0, pt_finalX[_pi], pt_yy[_pi], pt_scA[_pi], pt_scA[_pi], 0, c_white, pt_a[_pi]);
                            }
                        }
                        surface_reset_target();
                        gpu_set_texfilter(1);
                        if (doLogOnce == 1) { file_text_write_string(logFile, "PLOT NORMAL canvas (batched)"); file_text_writeln(logFile); }
                    }

                    // ID Map Draw
                    if (doID and id_GenState == 1) {
                        surface_set_target(id_canvas);
                        for (_pi = 0; _pi < pt_count; _pi++) {
                            if (moreHairs == 0) draw_sprite_ext(spr_strander, pt_sub[_pi], pt_finalX[_pi], pt_yy[_pi], pt_scA[_pi], pt_scA[_pi], 0, idChoice, pt_a[_pi]);
                            if (moreHairs == 1) draw_sprite_ext(spr_strander, pt_sub[_pi], pt_finalX[_pi], pt_yy[_pi], pt_scA[_pi], pt_scA[_pi], pt_ang[_pi] + pt_curl[_pi], idChoice, pt_a[_pi]);
                        }
                        surface_reset_target();
                        if (doLogOnce == 1) { file_text_write_string(logFile, "PLOT ID canvas (batched)"); file_text_writeln(logFile); }
                    }

                    // Flow Map Draw
                    if (doFlow and flow_GenState == 1) {
                        surface_set_target(flow_canvas);
                        gpu_set_blendmode(bm_normal);
                        for (_pi = 0; _pi < pt_count; _pi++) {
                            var pfx = pt_finalX[_pi]; var pyy = pt_yy[_pi]; var ppx = pt_prevX[_pi];
                            var psc = pt_scA[_pi]; var pa = pt_a[_pi]; var psub = pt_sub[_pi];
                            var pang = pt_ang[_pi] + pt_curl[_pi];
                            if (dirHue == 1) {
                                var remapAng = remap(point_direction(ppx, pyy - 1, pfx, pyy), 180, 360, 0, 1);
                                if (moreHairs == 0) draw_sprite_ext(spr_strander, psub, pfx, pyy, psc, psc, 0, make_color_hsv((254 * remapAng), 255, 255), pa);
                                if (moreHairs == 1) draw_sprite_ext(spr_strander, psub, pfx, pyy, psc, psc, pang, make_color_hsv((254 * remapAng), 255, 255), pa);
                            } else {
                                var lr = 0; var ud = 0;
                                if (moreHairs == 1) {
                                    lr = (sin((dirFlipX * 180) + degtorad(point_direction(ppx, pyy - 1, pfx, pyy) + (pang * curlRotAmt * 0.001))) + 1) / 2;
                                    ud = (cos((dirFlipY * 180) + degtorad(point_direction(ppx, pyy - 1, pfx, pyy) + (pang * curlRotAmt * 0.001))) + 1) / 2;
                                }
                                if (moreHairs == 0) {
                                    lr = (sin((dirFlipX * 180) + degtorad(point_direction(ppx, pyy - 1, pfx, pyy))) + 1) / 2;
                                    ud = (cos((dirFlipY * 180) + degtorad(point_direction(ppx, pyy - 1, pfx, pyy))) + 1) / 2;
                                }
                                gpu_set_blendmode(bm_normal);
                                if (moreHairs == 0) draw_sprite_ext(spr_strander, psub, pfx, pyy, psc, psc, 0, make_color_rgb(255 * ud, 255 * lr, 0), pa);
                                if (moreHairs == 1) draw_sprite_ext(spr_strander, psub, pfx, pyy, psc, psc, pang, make_color_rgb(255 * ud, 255 * lr, 0), pa);
                            }
                        }
                        surface_reset_target();
                        if (doLogOnce == 1) { file_text_write_string(logFile, "PLOT FLOW canvas (batched)"); file_text_writeln(logFile); }
                    }

                    // AO Map Draw
                    if (doAO and ao_GenState == 1) {
                        surface_set_target(ao_canvas);
                        for (_pi = 0; _pi < pt_count; _pi++) {
                            var pfx = pt_finalX[_pi]; var pyy = pt_yy[_pi]; var ppx = pt_prevX[_pi];
                            var psc = pt_scA[_pi]; var psub = pt_sub[_pi]; var pang = pt_ang[_pi] + pt_curl[_pi];
                            if (moreHairs == 0) {
                                var aoAmt = (10 - aoExtra) * 0.05;
                                var passes = clamp(round(10 * aoExtra), 6, 10);
                                for (pass = 1; pass < passes + 1; pass++) {
                                    if (tog == 1) {
                                        draw_sprite_ext(spr_aoPlotter, psub, pfx, pyy, psc * (pass / passes) * (aoExtra * (pass / passes)), psc * (pass / passes) * (aoExtra * (pass / passes)), point_direction(ppx, pyy - 1, pfx, pyy) + 90, c_white, aoAmt);
                                        aoAmt -= (0.16 / passes);
                                    }
                                    tog++;
                                    if (tog >= 7) tog = 1;
                                }
                            }
                            if (moreHairs == 1) {
                                draw_sprite_ext(spr_stranderAO, psub, pfx, pyy, psc, psc, pang, c_white, 0.88);
                                draw_sprite_ext(spr_stranderAO, psub, pfx, pyy, psc * 0.97, psc * 0.97, pang, c_black, 0.25);
                            }
                        }
                        surface_reset_target();
                        if (doLogOnce == 1) { file_text_write_string(logFile, "PLOT AO canvas (batched)"); file_text_writeln(logFile); }
                    }

                    // Mask Map Draw
                    if (doMask and mask_GenState == 1) {
                        surface_set_target(mask_canvas);
                        for (_pi = 0; _pi < pt_count; _pi++) {
                            if (moreHairs == 0) draw_sprite_ext(spr_strander, pt_sub[_pi], pt_finalX[_pi], pt_yy[_pi], pt_scA[_pi], pt_scA[_pi], 0, c_white, pt_a[_pi]);
                            if (moreHairs == 1) draw_sprite_ext(spr_strander, pt_sub[_pi], pt_finalX[_pi], pt_yy[_pi], pt_scA[_pi], pt_scA[_pi], pt_ang[_pi] + pt_curl[_pi], c_white, pt_a[_pi]);
                        }
                        surface_reset_target();
                        if (doLogOnce == 1) { file_text_write_string(logFile, "PLOT MASK canvas (batched)"); file_text_writeln(logFile); }
                    }

                    // Depth Map Draw
                    if (doDepth and depth_GenState == 1) {
                        surface_set_target(depth_canvas);
                        gpu_set_blendmode(bm_normal);
                        for (_pi = 0; _pi < pt_count; _pi++) {
                            if (moreHairs == 0) draw_sprite_ext(spr_strander, pt_sub[_pi], pt_finalX[_pi], pt_yy[_pi], pt_scA[_pi], pt_scA[_pi], 0, pt_depthTone[_pi], pt_a[_pi]);
                            if (moreHairs == 1) draw_sprite_ext(spr_strander, pt_sub[_pi], pt_finalX[_pi], pt_yy[_pi], pt_scA[_pi], pt_scA[_pi], pt_ang[_pi] + pt_curl[_pi], pt_depthTone[_pi], pt_a[_pi]);
                        }
                        surface_reset_target();
                        if (doLogOnce == 1) { file_text_write_string(logFile, "PLOT DEPTH canvas (batched)"); file_text_writeln(logFile); }
                    }

                    // Frizz Map Draw
                    if (doFrizz and frizz_GenState == 1) {
                        surface_set_target(frizz_canvas);
                        for (_pi = 0; _pi < pt_count; _pi++) {
                            frizzColor = make_color_hsv(0, 0, irandom(255));
                            if (moreHairs == 0) draw_sprite_ext(spr_strander, pt_sub[_pi], pt_finalX[_pi], pt_yy[_pi], pt_scA[_pi], pt_scA[_pi], 0, frizzColor, pt_a[_pi]);
                            if (moreHairs == 1) draw_sprite_ext(spr_strander, pt_sub[_pi], pt_finalX[_pi], pt_yy[_pi], pt_scA[_pi], pt_scA[_pi], pt_ang[_pi] + pt_curl[_pi], frizzColor, pt_a[_pi]);
                        }
                        surface_reset_target();
                        if (doLogOnce == 1) { file_text_write_string(logFile, "PLOT FRIZZ canvas (batched)"); file_text_writeln(logFile); }
                    }

                    strandCount++;

                    // ---------------------------------------------------------
                    // PROGRESS FEEDBACK BLITTING
                    // ---------------------------------------------------------
                    if (strandCount mod 20 == 0) {
                        var _activeCanvas;
                        // Canvas priority: colour > rgbmask > depth > others
                        if      (doColor  and color_GenState    == 1) _activeCanvas = color_canvas;
                        else if (doRGB    and rgbMask_GenState  == 1) _activeCanvas = canvas;
                        else if (doDepth  and depth_GenState    == 1) _activeCanvas = depth_canvas;
                        else if (doMask   and mask_GenState     == 1) _activeCanvas = mask_canvas;
                        else if (doNorm   and norm_GenState     == 1) _activeCanvas = nm_canvas;
                        else if (doID     and id_GenState       == 1) _activeCanvas = id_canvas;
                        else if (doFlow   and flow_GenState     == 1) _activeCanvas = flow_canvas;
                        else if (doAO     and ao_GenState       == 1) _activeCanvas = ao_canvas;
                        else if (doFrizz  and frizz_GenState    == 1) _activeCanvas = frizz_canvas;
                        else                                          _activeCanvas = canvas;

                        if (surface_exists(_activeCanvas)) {
                            // Centre viewport on the current set being generated
                            // setXpos is the set's X centre in 4096 space
                            // Show a 2048-wide window centred on it for context
                            var _srcW = 2048;
                            var _srcH = 4096;
                            var _srcX = clamp(setXpos - (_srcW * 0.5), 0, 4096 - _srcW);
                            var _srcY = 0;

                            surface_set_target(application_surface);
                            draw_clear(c_black);
                            draw_surface_part_ext(_activeCanvas, _srcX, _srcY, _srcW, _srcH, 0, 0, 1024/_srcW, 1024/_srcH, c_white, 1);

                            // Red "generating" overlay at low alpha
                            draw_set_color(c_red);
                            draw_set_alpha(0.15);
                            draw_rectangle(0, 0, 1024, 1023, 0);
                            draw_set_alpha(1);
                            draw_set_color(c_white);

                            // Progress bar
                            var _prog = clamp((renderF + (strandCount / max(strandSet, 1))) / (sets + 1), 0, 1);
                            draw_set_color(make_color_rgb(20, 20, 20));
                            draw_rectangle(20, 1000, 820, 1014, 0);
                            draw_set_color(make_color_rgb(80, 220, 120));
                            draw_rectangle(20, 1000, 20 + 800 * _prog, 1014, 0);
                            draw_set_color(c_white);
                            draw_set_font(-1);
                            draw_text(20, 980, "Generating... set " + string(renderF + 1) + " of " + string(sets + 1) + " | " + string(strandCount) + " strands");
                            surface_reset_target();
                        }
                    }
                } // End strand loop

                // Final viewport update for completed set
                var _activeCanvas;
                if      (doColor  and color_GenState   == 1) _activeCanvas = color_canvas;
                else if (doRGB    and rgbMask_GenState == 1) _activeCanvas = canvas;
                else if (doDepth  and depth_GenState   == 1) _activeCanvas = depth_canvas;
                else if (doMask   and mask_GenState    == 1) _activeCanvas = mask_canvas;
                else if (doNorm   and norm_GenState    == 1) _activeCanvas = nm_canvas;
                else if (doID     and id_GenState      == 1) _activeCanvas = id_canvas;
                else if (doFlow   and flow_GenState    == 1) _activeCanvas = flow_canvas;
                else if (doAO     and ao_GenState      == 1) _activeCanvas = ao_canvas;
                else if (doFrizz  and frizz_GenState   == 1) _activeCanvas = frizz_canvas;
                else                                         _activeCanvas = canvas;

                if (surface_exists(_activeCanvas)) {
				    var _srcW = 2048;
				    var _srcH = 4096;  // ← add this
				    var _srcX = clamp(setXpos - (_srcW * 0.5), 0, 4096 - _srcW);
				    surface_set_target(application_surface);
				    draw_clear(c_black);
				    draw_surface_part_ext(_activeCanvas, _srcX, 0, _srcW, _srcH, 0, 0, 1024/_srcW, 1024/_srcH, c_white, 1);
				    draw_set_color(c_white);
				    surface_reset_target();
				}

                // Set complete - advance to next frame
                renderF++;
                if (renderF <= sets) {
					xxx = (1024 / 11) * h
                    retrigger = true;
                    return;
                }
            } // End sets block

            // Final blue overwash for the Flow map if applicable
            if (dirBlue == 1 and !dirHue and doFlow == 1 and flow_GenState == 1) {
                surface_set_target(flow_canvas);
                gpu_set_blendmode(bm_add);
                draw_set_color(make_color_rgb(0, 0, 128));
                draw_rectangle(0, 0, 4095, 4095, 0);
                if (f == 0) { surfData = surfData + "_" + string(surface_get_target()); }
                surface_reset_target();
                gpu_set_blendmode(bm_normal);
                draw_set_color(c_white);
                if (doLogOnce == 1) { file_text_write_string(logFile, "ADD blue over Flowmap"); file_text_writeln(logFile); }
            }

            retrigger = false;
            j = 0; h = 0;
            canSave = true;

            // Transition GenStates to 'Complete' (State 2)
            if (rgbMask_GenState == 1) rgbMask_GenState = 2;
            if (norm_GenState == 1) norm_GenState = 2;
            if (color_GenState == 1) color_GenState = 2;
            if (mask_GenState == 1) mask_GenState = 2;
            if (id_GenState == 1) id_GenState = 2;
            if (depth_GenState == 1) depth_GenState = 2;
            if (flow_GenState == 1) flow_GenState = 2;
            if (ao_GenState == 1) ao_GenState = 2;
            if (frizz_GenState == 1) frizz_GenState = 2;
			imgOverride = -1; // release override, return to normal img
            renderF = 0;
            pleaseGen = false;

        } // End retrigger

        doOnce = false;
        if (doLogOnce == 1) { file_text_close(logFile); doLogOnce = 2; }
    } // End doOnce
}